### ISSUE TITLE
Issues in property_prediction.ipynb

### ISSUE THREAD

**Issue by shuan4638** [daenuprobst/molsetrep#2]
I was trying to reproduce the results with the example file property_prediction.ipynb, but there are a few technical and conceptual issues I found when I ran the code. It seems like these codes were released without being properly tested.

1. I assume the code `dims_single = [dataset_train_single[0][0].shape[0]]` should be `dims_single = [dataset_train_single[0][0].shape[1]]` as the variable seems to be the dimension of the descriptors. The dimension error will pop up if I use the original code to train the model.
2. I assume that `trainer_single.fit(model_dual, train_dataloaders=train_loader_single)` should be changed to `trainer_single.fit(model_single, train_dataloaders=train_loader_single)`.

**Comment by daenuprobst** [comment]
Dear @shuan4638, the issues have been fixed with the latest PR (#3).
